makecode:
  target: microbit
  platform: microbit
  home_url: https://makecode.microbit.org/
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
include:
  - assets
  - README.md
baseurl: /pxt-snore/docs/
